package com.fu.flix.constant.enums;

public enum NotificationStatus {
    REQUEST_CREATE_SUCCESS,
    REQUEST_APPROVED,
    REQUEST_CONFIRM_FIXING,
    CREATE_INVOICE,
    REQUEST_CANCELED,
    REQUEST_CANCELED_AUTOMATICALLY,
    REMIND_EXPECT_FIXING_TIME_DEADLINE,
    REMIND_FIXING_TASK,
    REQUEST_DONE,
    FEEDBACK_PROCESSING,
    FEEDBACK_REJECTED,
    FEEDBACK_DONE,
    FEEDBACK_PENDING,
    DEPOSIT_SUCCESS,
    DEPOSIT_FAILED,
    REGISTER_SUCCESS,
    REGISTER_FAIL
}
