package com.fu.flix.constant.enums;

public enum NotificationType {
    REQUEST_CREATE_SUCCESS,
    REQUEST_APPROVED,
    REQUEST_CONFIRM_FIXING,
    CREATE_INVOICE,
    REQUEST_CANCELED,
    REQUEST_DONE,
    FEEDBACK_PROCESSING,
    FEEDBACK_REJECTED,
    FEEDBACK_DONE,
    FEEDBACK_PENDING,
    DEPOSIT_SUCCESS,
    DEPOSIT_FAILED,
}
