app:
  secretKey: 'secret'
  lifeTimeToke: 86400000 #milliseconds
  lifeTimeRefreshToken: 172800000 #milliseconds
  limitQueryDefault: 20
  offsetDefault: 0
  vat: 0.05
  profitRate: 0.2
  fine: 20000
  minTimeFined: 3600 #milliseconds
  twilioInfo:
    accountSid: 'AC61a6f887f88c2c98f13b8c807cb8e15d'
    authToken: 'b2bdec58830ce248a8e2d60bdfa6205c'
    fromNumber: '+17579977028'
  firebaseConfig: 'flix-cb844-firebase-adminsdk-297yq-b523f2743e.json'
  defaultAvatar: 1
  permitAllApis: [ '/api/v1/login',
                   '/api/v1/token/refresh',
                   '/api/v1/register/sendOTP',
                   '/api/v1/register/confirm',
                   '/swagger-ui/index.html',
                   '/v2/api-docs',
                   '/swagger-resources',
                   '/api/v1/forgot/password/sendOTP',
                   '/api/v1/forgot/password/confirm',
                   '/api/v1/address/city',
                   '/api/v1/address/district',
                   '/api/v1/address/commune',
                   '/api/v1/payment/response' ]
  vnPayInfo:
    version: '2.1.0'
    command: 'pay'
    tmnCode: '1TZDUKO5'
    locate: 'vn'
    vnPayAmountRate: 100
    datePattern: 'yyyyMMddHHmmss'
    currCode: 'VND'
    secureHash: 'MPBTQAIUBXZUPPPWJEGMCTPCDZRNRLZV'
    payUrl: 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
    returnUrl: 'https://www.facebook.com/'

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://34.142.171.163:3306/flix_db
    username: root
    password: S$s.(QQl6mXrG,eJ
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 34.134.183.253
    port: 6379
    password: ''
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
